
import { Language, Continent, Category, TimeRange } from './types';

export const TRANSLATIONS = {
  [Language.EN]: {
    appTitle: "EPM Global",
    businessTitle: "Corporate Intelligence",
    communityTitle: "Global Network",
    aiChatTitle: "Strategic Assistant",
    filterTitle: "Strategic Filters",
    timeFilter: "Analysis Period",
    continent: "Market Region",
    country: "Specific Territory",
    category: "Strategic Theme",
    subCategory: "Niche Analysis",
    readMore: "Strategic Report",
    trends: "Market Liquidity & Price Volatility",
    priceIndex: "Capital Flow",
    growth: "GDP Projection",
    latestNews: "EPM Global Signal",
    noResults: "No strategic data found for this segment.",
    loading: "Syncing global markets...",
    all: "Global",
    allCountries: "All Territories",
    locationPlaceholder: "City, Country or Niche...",
    detectLocation: "Geo-Sync",
    localNews: "Regional Strategy",
    realtime: "Grounded IA Node: Active",
    timeToday: "24h Cycle",
    timeWeek: "Weekly Trend",
    timeMonth: "Monthly Outlook",
    viewSummary: "Executive Summary",
    viewSource: "Reference Source",
    viewPros: "Opportunities (+)",
    viewCons: "Risk Matrix (-)",
    viewForecast: "ROI Forecasts",
    strategicAnalysis: "Market Pulse Analysis",
    globalChat: "Global Signal Stream",
    friends: "Strategic Contacts",
    addFriend: "Request Alliance",
    sendMessage: "Transmit Data",
    aiAssistant: "EPM AI Assistant",
    aiPrompt: "Ask anything about markets, sports, or global strategy...",
    // Sections
    sectionGeneral: "Global Intelligence",
    sectionBusiness: "Business Area",
    sectionAI: "AI Core"
  },
  [Language.PT]: {
    appTitle: "EPM Global",
    businessTitle: "Inteligência Corporativa",
    communityTitle: "Rede Global",
    aiChatTitle: "Assistente Estratégico",
    filterTitle: "Filtros Estratégicos",
    timeFilter: "Período de Análise",
    continent: "Região de Mercado",
    country: "Território Específico",
    category: "Tema Estratégico",
    subCategory: "Análise de Nicho",
    readMore: "Relatório Estratégico",
    trends: "Liquidez de Mercado e Volatilidade",
    priceIndex: "Fluxo de Capital",
    growth: "Projeção de PIB",
    latestNews: "Sinal EPM Global",
    noResults: "Nenhum dado estratégico encontrado para este segmento.",
    loading: "Sincronizando mercados globais...",
    all: "Global",
    allCountries: "Todos os Territórios",
    locationPlaceholder: "Cidade, País ou Nicho...",
    detectLocation: "Sinc. Geo",
    localNews: "Estratégia Regional",
    realtime: "Nodo IA Grounded: Ativo",
    timeToday: "Ciclo 24h",
    timeWeek: "Tendência Semanal",
    timeMonth: "Panorama Mensal",
    viewSummary: "Resumo Executivo",
    viewSource: "Fonte de Referência",
    viewPros: "Pontos de Alavancagem (+)",
    viewCons: "Riscos Críticos (-)",
    viewForecast: "Previsões de Retorno",
    strategicAnalysis: "Análise de Pulso de Mercado",
    globalChat: "Fluxo de Sinal Global",
    friends: "Contatos Estratégicos",
    addFriend: "Solicitar Aliança",
    sendMessage: "Transmitir Dados",
    aiAssistant: "Assistente EPM AI",
    aiPrompt: "Pergunte qualquer coisa sobre mercados, esportes ou estratégia global...",
    // Sections
    sectionGeneral: "Inteligência Global",
    sectionBusiness: "Área de Negócios",
    sectionAI: "Núcleo IA"
  },
  [Language.ES]: {
    appTitle: "EPM Global",
    businessTitle: "Inteligencia Corporativa",
    communityTitle: "Red Global",
    aiChatTitle: "Asistente Estratégico",
    filterTitle: "Filtros Estratégicos",
    timeFilter: "Período de Análisis",
    continent: "Región de Mercado",
    country: "Territorio Específico",
    category: "Tema Estratégico",
    subCategory: "Análisis de Nicho",
    readMore: "Informe Estratégico",
    trends: "Liquidez y Volatilidad de Precios",
    priceIndex: "Flujo de Capital",
    growth: "Proyección de PIB",
    latestNews: "Señal EPM Global",
    noResults: "No se encontraron datos estratégicos.",
    loading: "Sincronizando mercados globales...",
    all: "Global",
    allCountries: "Todos los Territorios",
    locationPlaceholder: "Ciudad, País o Nicho...",
    detectLocation: "Sinc. Geo",
    localNews: "Análisis Regional",
    realtime: "IA Grounded: Activa",
    timeToday: "Ciclo 24h",
    timeWeek: "Tendencia Semanal",
    timeMonth: "Perspectiva Mensual",
    viewSummary: "Resumen Ejecutivo",
    viewSource: "Fuente de Referencia",
    viewPros: "Oportunidades (+)",
    viewCons: "Matriz de Riesgos (-)",
    viewForecast: "Previsiones de ROI",
    strategicAnalysis: "Análisis de Pulso Estratégico",
    globalChat: "Flujo de Señal Global",
    friends: "Contactos Estratégicos",
    addFriend: "Solicitar Alianza",
    sendMessage: "Transmitir Datos",
    aiAssistant: "Asistente EPM AI",
    aiPrompt: "Pregunta cualquier cosa sobre mercados, deportes o estrategia global...",
    // Sections
    sectionGeneral: "Inteligencia Global",
    sectionBusiness: "Área de Negocios",
    sectionAI: "Núcleo IA"
  },
  [Language.FR]: {
    appTitle: "EPM Global",
    businessTitle: "Intelligence D'Entreprise",
    communityTitle: "Réseau Mondial",
    aiChatTitle: "Assistant Stratégique",
    filterTitle: "Filtres Stratégiques",
    timeFilter: "Période d'Analyse",
    continent: "Région du Marché",
    country: "Territoire Spécifique",
    category: "Thème Stratégique",
    subCategory: "Analyse de Niche",
    readMore: "Rapport Stratégique",
    trends: "Liquidité et Volatilité",
    priceIndex: "Flux de Capitaux",
    growth: "Projection PIB",
    latestNews: "Signal EPM Global",
    noResults: "Aucune donnée stratégique trouvée.",
    loading: "Synchronisation des marchés...",
    all: "Mondial",
    allCountries: "Tous les Territoires",
    locationPlaceholder: "Ville, Pays ou Niche...",
    detectLocation: "Géo-Sync",
    localNews: "Stratégie Régionale",
    realtime: "Nœud IA: Actif",
    timeToday: "Cycle 24h",
    timeWeek: "Tendance Hebdo",
    timeMonth: "Perspective Mensuelle",
    viewSummary: "Résumé Exécutif",
    viewSource: "Source de Référence",
    viewPros: "Opportunités (+)",
    viewCons: "Matrice de Risques (-)",
    viewForecast: "Prévisions ROI",
    strategicAnalysis: "Analyse du Pouls",
    globalChat: "Flux de Signal",
    friends: "Contacts Stratégiques",
    addFriend: "Demande d'Alliance",
    sendMessage: "Transmettre",
    aiAssistant: "Assistant EPM AI",
    aiPrompt: "Demandez n'importe quoi sur les marchés ou la stratégie...",
    // Sections
    sectionGeneral: "Intelligence Globale",
    sectionBusiness: "Espace Affaires",
    sectionAI: "Noyau IA"
  },
  [Language.DE]: {
    appTitle: "EPM Global",
    businessTitle: "Unternehmensintelligenz",
    communityTitle: "Globales Netzwerk",
    aiChatTitle: "Strategischer Assistent",
    filterTitle: "Strategische Filter",
    timeFilter: "Analysezeitraum",
    continent: "Marktregion",
    country: "Spezifisches Gebiet",
    category: "Strategisches Thema",
    subCategory: "Nischenanalyse",
    readMore: "Strategischer Bericht",
    trends: "Marktliquidität",
    priceIndex: "Kapitalfluss",
    growth: "BIP-Prognose",
    latestNews: "EPM Global Signal",
    noResults: "Keine strategischen Daten gefunden.",
    loading: "Märkte werden synchronisiert...",
    all: "Global",
    allCountries: "Alle Gebiete",
    locationPlaceholder: "Stadt, Land oder Nische...",
    detectLocation: "Geo-Sync",
    localNews: "Regionale Strategie",
    realtime: "KI-Knoten: Aktiv",
    timeToday: "24h Zyklus",
    timeWeek: "Wochentrend",
    timeMonth: "Monatsausblick",
    viewSummary: "Zusammenfassung",
    viewSource: "Referenzquelle",
    viewPros: "Chancen (+)",
    viewCons: "Risikomatrix (-)",
    viewForecast: "ROI-Prognosen",
    strategicAnalysis: "Marktpulsanalyse",
    globalChat: "Signalstrom",
    friends: "Strategische Kontakte",
    addFriend: "Allianz anfordern",
    sendMessage: "Senden",
    aiAssistant: "EPM KI-Assistent",
    aiPrompt: "Fragen Sie alles über Märkte, Sport oder Strategie...",
    // Sections
    sectionGeneral: "Globale Intelligenz",
    sectionBusiness: "Geschäftsbereich",
    sectionAI: "KI-Kern"
  }
};

export const CONTINENTS = Object.values(Continent);
export const CATEGORIES = Object.values(Category);

export const COUNTRIES_BY_CONTINENT: Record<Continent, string[]> = {
  [Continent.GLOBAL]: [],
  [Continent.AFRICA]: ["South Africa", "Nigeria", "Kenya", "Egypt", "Morocco", "Ghana", "Ethiopia"],
  [Continent.ASIA]: ["Japan", "China", "India", "Singapore", "South Korea", "Saudi Arabia", "UAE", "Indonesia", "Vietnam"],
  [Continent.EUROPE]: ["UK", "Germany", "France", "Italy", "Spain", "Netherlands", "Switzerland", "Sweden", "Poland"],
  [Continent.NORTH_AMERICA]: ["USA", "Canada", "Mexico"],
  [Continent.SOUTH_AMERICA]: ["Brazil", "Argentina", "Chile", "Colombia", "Peru", "Uruguay"],
  [Continent.OCEANIA]: ["Australia", "New Zealand", "Fiji"]
};

export const SUB_CATEGORIES: Record<Category, string[]> = {
  [Category.GLOBAL]: ["Everything", "Trending", "Breaking"],
  [Category.BUSINESS]: ["Finance", "Startups", "Real Estate", "M&A", "Logistics"],
  [Category.ECONOMY]: ["Inflation", "Interest Rates", "Fiscal Policy", "Trade", "Energy"],
  [Category.TECHNOLOGY]: ["AI", "Web3", "Gadgets", "Cloud", "Cybersecurity"],
  [Category.SPORTS]: ["Football", "Handball", "Basketball", "Tennis", "F1", "Olympics"],
  [Category.POLITICS]: ["Elections", "Geopolitics", "Legislative", "Diplomacy"],
  [Category.HEALTH]: ["Biotech", "Pandemics", "Wellness", "Insurance", "Research"],
  [Category.CULTURE]: ["Art", "Cinema", "Music", "Lifestyle", "Fashion"],
  [Category.MARKET_SENTIMENT]: ["Stocks", "Crypto", "Commodities", "Forex"],
  [Category.AGRIBUSINESS]: ["Commodities", "AgriTech", "Exports", "Sustainability", "Supply Chain"],
  [Category.TRAVEL]: ["Aviation", "Hospitality", "Tourism Trends", "Luxury", "Business Travel"],
  [Category.MARKETING]: ["Digital Ads", "Branding", "Social Media", "SEO", "Consumer Behavior"]
};

export const TIME_RANGES = [
  { value: TimeRange.TODAY, labelKey: 'timeToday' },
  { value: TimeRange.WEEK, labelKey: 'timeWeek' },
  { value: TimeRange.MONTH, labelKey: 'timeMonth' }
];
